/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PlanoAnoRouteImport } from './routes/plano-ano'
import { Route as TurmaRouteImport } from './routes/turma'
import { Route as AtividadesIndexRouteImport } from './routes/atividades.index'
import { Route as AtividadesIdRouteImport } from './routes/atividades.$id'
import { Route as AtividadesNovaRouteImport } from './routes/atividades.nova'
import { Route as FolhaIdRouteImport } from './routes/folha.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoAnoRoute = PlanoAnoRouteImport.update({
  id: '/plano-ano',
  path: '/plano-ano',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmaRoute = TurmaRouteImport.update({
  id: '/turma',
  path: '/turma',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIdRoute = AtividadesIdRouteImport.update({
  id: '/atividades/$id',
  path: '/atividades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesNovaRoute = AtividadesNovaRouteImport.update({
  id: '/atividades/nova',
  path: '/atividades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const FolhaIdRoute = FolhaIdRouteImport.update({
  id: '/folha/$id',
  path: '/folha/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/calendario': typeof CalendarioRoute
  '/materiais': typeof MateriaisRoute
  '/perfil': typeof PerfilRoute
  '/planejamento': typeof PlanejamentoRoute
  '/plano-ano': typeof PlanoAnoRoute
  '/turma': typeof TurmaRoute
  '/atividades/$id': typeof AtividadesIdRoute
  '/atividades/nova': typeof AtividadesNovaRoute
  '/folha/$id': typeof FolhaIdRoute
  '/atividades/': typeof AtividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/calendario': typeof CalendarioRoute
  '/materiais': typeof MateriaisRoute
  '/perfil': typeof PerfilRoute
  '/planejamento': typeof PlanejamentoRoute
  '/plano-ano': typeof PlanoAnoRoute
  '/turma': typeof TurmaRoute
  '/atividades/$id': typeof AtividadesIdRoute
  '/atividades/nova': typeof AtividadesNovaRoute
  '/folha/$id': typeof FolhaIdRoute
  '/atividades': typeof AtividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/calendario': typeof CalendarioRoute
  '/materiais': typeof MateriaisRoute
  '/perfil': typeof PerfilRoute
  '/planejamento': typeof PlanejamentoRoute
  '/plano-ano': typeof PlanoAnoRoute
  '/turma': typeof TurmaRoute
  '/atividades/$id': typeof AtividadesIdRoute
  '/atividades/nova': typeof AtividadesNovaRoute
  '/folha/$id': typeof FolhaIdRoute
  '/atividades/': typeof AtividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/calendario'
    | '/materiais'
    | '/perfil'
    | '/planejamento'
    | '/plano-ano'
    | '/turma'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/folha/$id'
    | '/atividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/calendario'
    | '/materiais'
    | '/perfil'
    | '/planejamento'
    | '/plano-ano'
    | '/turma'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/folha/$id'
    | '/atividades'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/calendario'
    | '/materiais'
    | '/perfil'
    | '/planejamento'
    | '/plano-ano'
    | '/turma'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/folha/$id'
    | '/atividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  CalendarioRoute: typeof CalendarioRoute
  MateriaisRoute: typeof MateriaisRoute
  PerfilRoute: typeof PerfilRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  PlanoAnoRoute: typeof PlanoAnoRoute
  TurmaRoute: typeof TurmaRoute
  AtividadesIdRoute: typeof AtividadesIdRoute
  AtividadesNovaRoute: typeof AtividadesNovaRoute
  FolhaIdRoute: typeof FolhaIdRoute
  AtividadesIndexRoute: typeof AtividadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-ano': {
      id: '/plano-ano'
      path: '/plano-ano'
      fullPath: '/plano-ano'
      preLoaderRoute: typeof PlanoAnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turma': {
      id: '/turma'
      path: '/turma'
      fullPath: '/turma'
      preLoaderRoute: typeof TurmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$id': {
      id: '/atividades/$id'
      path: '/atividades/$id'
      fullPath: '/atividades/$id'
      preLoaderRoute: typeof AtividadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/nova': {
      id: '/atividades/nova'
      path: '/atividades/nova'
      fullPath: '/atividades/nova'
      preLoaderRoute: typeof AtividadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folha/$id': {
      id: '/folha/$id'
      path: '/folha/$id'
      fullPath: '/folha/$id'
      preLoaderRoute: typeof FolhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  CalendarioRoute: CalendarioRoute,
  MateriaisRoute: MateriaisRoute,
  PerfilRoute: PerfilRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  PlanoAnoRoute: PlanoAnoRoute,
  TurmaRoute: TurmaRoute,
  AtividadesIdRoute: AtividadesIdRoute,
  AtividadesNovaRoute: AtividadesNovaRoute,
  FolhaIdRoute: FolhaIdRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
